### PR TITLE
Global va

### PR DESCRIPTION
**Pull request by FGDATA**
@Raystm2 

Dear Ray
Earlier today I received your pull request. After merging it, I had to revert it. 
Because, your request merged your version (branch globalVA) into the master branch of FGMEMBERS. 
The master branch is the most recent work by SydAdams, and thus such merge is not convenient. 

I verified to apply your merge into the globalVA branch, but it seems everything was up to date (that is, no new changes are applied into globalVA)

I had merged the master branch recent commits into globalVA, and thus, to sync your version to FGMEMBERs, I am creating this pull request.

Note: As expected, this merge attempts to merge from FGMEMBERS globalVA branch into Raystm2 globalVA branch. 

If you need to revise your previous merge and my revert, I isolated it in a temporal branch 
here: https://github.com/FGMEMBERS/b1900d/tree/revert-1-globalVA

If you see any change I am unintendenly ignoring, and you expect it to be merged into the globalVA branch, let me know

Best
@IAHM-COL

### CODE REVIEW

**Comment by Raystm2** [comment]
Dear Israel,
I'm sure the problem is my not completely understanding of how all this works. I had really attempted to replace the GVA190.png that had a bad url in the picture with a corrected GVA190.png that is in my personal archive on my computer. I had only wanted this livery to go into the branch GVA. I am sorry if I had mistakenly sent the request to master. I have no intention of wanting the new livery png to go to master. If Syd wants that livery he can indeed have it but I do not for see Syd wanting this iivery :)

I have somehow made an error. I will wait to re-apply the new livery going from my machine to the GVA branch until after I talk to you, or learn better what I did wrong. 

Thank you for not letting this merge take place as the error is mine. 

Ray

**Comment by Raystm2** [comment]
TO ADD to the above statement: 

 I believe a change to a binary file will not show up as a change to the archive.

**Comment by Raystm2** [comment]
Dear Israel, 
You had mentioned you had merged master into GVAbranch and that is fine but there is one issue that I have to watch out for and that is the entire reason for the GVAbranch. The GVAbranch depends that the autopilot roll modes steer by Aileron and not by Aileron-trim. it is the only reason for the branch, well that and the fact that this version has a working A/P with all the functions where as Master does not. I worry that master can pollute the GVA branch. The GVA branch is based on a much much earlier version of the aircraft. Really, the branch aircraft should never inherit from MASTER. It should be another plane version, seperate.

Thanks Ray

**Comment by IAHM-COL** [comment]
@Raystm2 
Don't worry about this merge polluting the global branch
Note there are 0 changes to the code. :+1:  

github1

It will just bring the globalVA of both your repo and my repo in sync. That's basically all. 

The change applicable over https://github.com/FGMEMBERS/b1900d/commit/ee022f9dbc3f06f8c63b551dbfd23bd976589e55 is valid for all repos/all branches, and had nothing to do with versions. Just with executable modes. And it was corrected over SVN at revision 583 as indicated in the long commit message left by E. Avergne.

This merge can be accepted without fear of consequences over the globalVA aircraft.

**Comment by IAHM-COL** [comment]
@Raystm2 
I will leave you a note about the rest of your PNG change (which you had not done yet) over the forum post you created ;)

**Pull request merged**
